steps:
  - trigger: "packer-centos-buildkite"
    label: ":sidekiq: :packer: Builds centos buildkite agent VM template"

  - wait

  - label: ":bowtie: :github: Read credentials"
    command: wget http://192.168.1.30:8000/scripts/terraform_vcenter_cred.sh -O /tmp/terraform_vcenter_cred.sh && chmod u+x /tmp/terraform_vcenter_cred.sh

  - wait

  - label: ":rage3: :terraform: Destroy VM"
    command: . /tmp/terraform_vcenter_cred.sh && terraform init && terraform destroy -input=false -var template_name=centos-buildkite-agent -var vm_name=centos-buildkite-agent -var vsphere_datastore=esx-nfs-1 -auto-approve
    agents:
      master: "true"

  - wait

  - label: ":partyparrot: :partyparrot: :partyparrot: :terraform: Deploy VM"
    command: . /tmp/terraform_vcenter_cred.sh && terraform init && terraform apply -input=false -var template_name=centos-buildkite-agent -var vm_name=centos-buildkite-agent -var vsphere_datastore=esx-nfs-1 -auto-approve
    agents:
      master: "true"